### ISSUE TITLE
Interstitial Timeout 

### ISSUE THREAD

**Issue by lucaleonardi** [poingstudios/godot-admob-plugin#137]
### Is your feature request related to a problem? If so, please describe.

I'm working on a platform game for Android and I try to load an interstitial on level loading. What can happen though, is that maybe the player is offline, or maybe the ad takes too long to load; I don't want this to interfere with the gameplay experience, so as soon as the level is loaded, I want the game to start, either if the interstitial is loaded or not.

### What feature or improvement would you like to see?

Is it possible to set a timeout value for an Interstitial load? In a way that, after a certain amount of seconds, if the interstitial is not loaded, the load call is stopped? Or maybe a method to stop it manually, like `stop_load_interstitial()`?

**Comment by gumaciel** [comment]
Hi, this can be useful for you: https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#awaiting-for-signals-or-coroutines

And you can use this callback `on_ad_failed_to_load`: https://poing-studios.github.io/godot-admob-plugin/ad_formats/interstitial/#load-an-ad

**Comment by gumaciel** [comment]
Hey! Thank you for your reply.

Right now, we can't make an ad stop loading. If the ad doesn't load, it will send a signal called `interstitial_failed_to_load`. Unfortunately, we can't do anything about this because Google manages it and doesn't give us control over it.

This suggestion you're proposing doesn't seem necessary for our code because it could make control of plugin code confusing/complex. It would be best if you manage it on your own.

I'll attach a video and a code example I made. The video is on desktop, but it should also work for mobile devices since I'm simulating the delay of the ad loading.

```gdscript
extends Node2D

var timer := Timer.new()

func _ready() -> void:
	_initialize_mobile_ads()
	_configure_timer()
	_try_load_interstitial()
	
func _initialize_mobile_ads() -> void:
	MobileAds.initialize()
	# warning-ignore:return_value_discarded
	MobileAds.connect("interstitial_failed_to_load", self, "_on_MobileAds_interstitial_failed_to_load")
	# warning-ignore:return_value_discarded
	MobileAds.connect("interstitial_loaded", self, "_on_MobileAds_interstitial_loaded")
	
func _on_MobileAds_interstitial_failed_to_load(error_code):
	print("Interstitial failed to load, error_code = " + str(error_code))
	_on_timer_timeout()
	
func _on_MobileAds_interstitial_loaded() -> void:
	print("Interstitial loaded, now can be showed")
	#MobileAds.show_interstitial() 
	_on_timer_timeout()
	
func _try_load_interstitial() -> void:
	MobileAds.load_interstitial()
	timer.start()

func _configure_timer() -> void:
	# warning-ignore:return_value_discarded
	timer.connect("timeout", self, "_on_timer_timeout")
	timer.wait_time = 5 #SECONDS
	timer.one_shot = true
	add_child(timer)

func _on_timer_timeout() -> void:
	timer.stop()
	# warning-ignore:return_value_discarded
	get_tree().change_scene("res://AnotherScene.tscn")
```

It's just an example, you can change however you want.

If this still doesn't meet your needs, feel free to let me know, thank you!

https://github.com/poing-studios/godot-admob-plugin/assets/20030153/257e9cdf-5b34-4877-a77d-6b23d93329bc

**Comment by lucaleonardi** [comment]
Thank you for the reply, but this doesn't solve the issue, it's just the same solution I proposed with a different code structure.
In this example, the ad would still load in the background even if you change scene, which is the exact problem I was trying to solve with the use of a `stop_loading()` function.

If the Google plugin doesn't give you control over this, I guess there's no much that can be done 😅 

I will go with this solution, at least the player doesn't risk to remain stuck in the loading screen for too long... even tho it's not an ideal solution, and could cause performance issues while the ad is still loading in the background.
